package com.example.ninjacarscalculator.models

data class Params(
    val id: Long? = null,
    var dateManufact: Long? = null,
    var engineCapacity: Long? = null,
    var carPrice: Long? = null,
    var freightVL: Long? = null,
    var FOB: Long? = null,
    var customsFee: Double? = null,
    var brokerageServicesRegistration: Long? = null,
    var customsСoefficient: Long? = null,
    var finalPrice: Long? = null,
    var banksСommission: Double? = null,
    var buttonComission: Long? = null,
    var deliveryСity: Long? = null,
    var addServices: Long? = null,
    var rusMoney: Long? = null,
    var japanMoney: Long? = null,
    var FOB2: Long? = null,
    var fastBid: Long? = null,
    var transfertCar: Long? = null,
    var nego: Long? = null,
    var newCustomer: Long? = null,
    var util: Long? = null,
    var customsClearance: Long? = null,
    var sbkts: Long? = null,
    var svh: Long? = null,
    var lab: Long? = null,
    var transfertTK: Long? = null,
    var broker: Long? = null,
    var glonas: Long? = null,
    var registr: Long? = null,
    var myFee: Long? = null,
    var euro: Double? = null,
    var usd: Double? = null,
    var yen: Double? = null,
) {

}

